### ISSUE TITLE
NotificationEventDataObject' is empty

### ISSUE THREAD

**Issue by joel-bach** [Haskell-OpenAPI-Code-Generator/Stripe-Haskell-Library#2]
The type `NotificationEventDataObject'` (https://hackage.haskell.org/package/stripeapi-0.1.0.2/docs/StripeAPI-Types-NotificationEventData.html#t:NotificationEventDataObject-39-) is empty and therefore not usable to extract information from the response. The relevant part from the Stripe specification is the following:

```yaml
    notification_event_data:
      description: ''
      properties:
        object:
          description: Object containing the API resource relevant to the event. For
            example, an `invoice.created` event will have a full [invoice object](https://stripe.com/docs/api#invoice_object)
            as the value of the object key.
          type: object
        previous_attributes:
          description: Object containing the names of the attributes that have changed,
            and their previous values (sent along only with *.updated events).
          type: object
      required:
      - object
      title: NotificationEventData
      type: object
      x-expandableFields: []
```

The generated code corresponds to the specification but is not usable nevertheless. One possible solution would be to adjust the generator to use `Data.Aeson.Value` instead of unit types.
